#  ██████╗ ██╗ ██████╗███████╗     ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
#  ██╔══██╗██║██╔════╝██╔════╝    ██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
#  ██████╔╝██║██║     █████╗      ██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
#  ██╔══██╗██║██║     ██╔══╝      ██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
#  ██║  ██║██║╚██████╗███████╗    ╚██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
#  ╚═╝  ╚═╝╚═╝ ╚═════╝╚══════╝     ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
#  Author   : z0mbi3
#  Modified : adilhyz
#  Info     : Alacritty Colorschemes for the 6 rices.

schemes:
# Colors (Aing) Aing Rice
  aing_dark: &aing_dark
    primary:
      background: '#161a22'
      foreground: '#cadee7'
    normal:
      black:   '#1e232e'
      red:     '#927887'
      green:   '#6E91BA'
      yellow:  '#A393A2'
      blue:    '#D2ACA9'
      magenta: '#E3C4BA'
      cyan:    '#99A9CC'
      white:   '#edf4f7'
    bright:
      black:   '#8d9ba1'
      red:     '#927887'
      green:   '#6E91BA'
      yellow:  '#A393A2'
      blue:    '#D2ACA9'
      magenta: '#E3C4BA'
      cyan:    '#99A9CC'
      white:   '#cadee7'
    cursor:
      cursor: '#cadee7'
      text: '#cadee7'
# Colors (Rose-Pine Moon) Esostrefis Rice
  esostrefis_rose_pine: &esostrefis_rose_pine
    primary:
      background: '#1f1d29'
      foreground: '#eaeaea'
    normal:
      black:   '#6f6e85'
      red:     '#ea6f91'
      green:   '#9bced7'
      yellow:  '#f1ca93'
      blue:    '#34738e'
      magenta: '#c3a5e6'
      cyan:    '#eabbb9'
      white:   '#faebd7'
    bright:
      black:   '#6f6e85'
      red:     '#ea6f91'
      green:   '#9bced7'
      yellow:  '#f1ca93'
      blue:    '#34738e'
      magenta: '#c3a5e6'
      cyan:    '#ebbcba'
      white:   '#e0def4'
    cursor:
      cursor: '#c3a5e6'
      text: '#1f1d29'
# Colors (CyberPunk) Jan Rice
  jan_cyberpunk: &jan_cyberpunk
    primary:
      background: '#070219'
      foreground: '#c0caf5'
    normal:
      black:   '#626483'
      red:     '#fb007a'
      green:   '#a6e22e'
      yellow:  '#f3e430'
      blue:    '#58AFC2'
      magenta: '#583794'
      cyan:    '#926BCA'
      white:   '#d9d9d9'
    bright:
      black:   '#626483'
      red:     '#fb007a'
      green:   '#a6e22e'
      yellow:  '#f3e430'
      blue:    '#58AFC2'
      magenta: '#472575'
      cyan:    '#926BCA'
      white:   '#f1f1f1'
    cursor:
      cursor: '#fb007a'
      text: '#070219'
# Colors (Elenapan) Pamela Rice
  pamela_color_scheme: &pamela_color_scheme
    primary:
      background: '#1D1F28'
      foreground: '#FDFDFD'
    normal:
      black:   '#3D4C5F'
      red:     '#F37F97'
      green:   '#5ADECD'
      yellow:  '#F2A272'
      blue:    '#8897F4'
      magenta: '#C574DD'
      cyan:    '#79E6F3'
      white:   '#FDFDFD'
    bright:
      black:   '#56687E'
      red:     '#FF4971'
      green:   '#18E3C8'
      yellow:  '#FF8037'
      blue:    '#556FFF'
      magenta: '#B043D1'
      cyan:    '#3FDCEE'
      white:   '#BEBEC1'
    cursor:
      cursor: '#FF4971'
      text: '#1D1F28'
# Colors (Dina-Hawu color scheme) Siduru Rice
  siduru_dinahawu: &siduru_dinahawu
    primary:
      background: '#e9eae3'
      foreground: '#0c0e1a'
    normal:
      black:   '#f3e9dc'
      red:     '#838382'
      green:   '#A29E9D'
      yellow:  '#BEB7B2'
      blue:    '#EAD4BA'
      magenta: '#97D4E1'
      cyan:    '#ECDDC1'
      white:   '#181e1c'
    bright:
      black:   '#f3e9dc'
      red:     '#838382'
      green:   '#A29E9D'
      yellow:  '#BEB7B2'
      blue:    '#EAD4BA'
      magenta: '#97D4E1'
      cyan:    '#ECDDC1'
      white:   '#aaa39a'
    cursor:
      cursor: '#bed5e5'
      text: '#bed5e5'
# Colors (Gruvbox) Silvia Rice
  silvia_gruvbox: &silvia_gruvbox
    primary:
      background: '#282828'
      foreground: '#fbf1c7'
    normal:
      black:   '#a89984'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#ebdbb2'
    bright:
      black:   '#a89984'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'
    cursor:
      cursor: '#fbf1c7'
      text: '#282828'

# Set the color scheme for the actual rice.
colors: *siduru_dinahawu