#  ██████╗ ██╗ ██████╗███████╗     ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
#  ██╔══██╗██║██╔════╝██╔════╝    ██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
#  ██████╔╝██║██║     █████╗      ██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
#  ██╔══██╗██║██║     ██╔══╝      ██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
#  ██║  ██║██║╚██████╗███████╗    ╚██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
#  ╚═╝  ╚═╝╚═╝ ╚═════╝╚══════╝     ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
#  Author   : z0mbi3
#  Modified : adilhyz
#  Info     : Alacritty Colorschemes for the 6 rices.

schemes:
# Colors (Rose-Pine Moon) Esostrefis Rice
  esostrefis_rose_pine: &esostrefis_rose_pine
    primary:
      background: '#1f1d29'
      foreground: '#eaeaea'
    normal:
      black:   '#6f6e85'
      red:     '#ea6f91'
      green:   '#9bced7'
      yellow:  '#f1ca93'
      blue:    '#34738e'
      magenta: '#c3a5e6'
      cyan:    '#eabbb9'
      white:   '#faebd7'
    bright:
      black:   '#6f6e85'
      red:     '#ea6f91'
      green:   '#9bced7'
      yellow:  '#f1ca93'
      blue:    '#34738e'
      magenta: '#c3a5e6'
      cyan:    '#ebbcba'
      white:   '#e0def4'
    cursor:
      cursor: '#c3a5e6'
      text: '#1f1d29'
# Colors (Onedark) Isabel Rice
  isabel_onedark: &isabel_onedark
    primary:
      background: '#14171c'
      foreground: '#b8bfe5'
    normal:
      black:   '#5c6370'
      red:     '#be5046'
      green:   '#81ae5f'
      yellow:  '#d19a66'
      blue:    '#4889be'
      magenta: '#7560d3'
      cyan:    '#49919a'
      white:   '#c5cddb'
    bright:
      black:   '#5c6370'
      red:     '#e06c75'
      green:   '#98c379'
      yellow:  '#e5c07b'
      blue:    '#61afef'
      magenta: '#8677cf'
      cyan:    '#56b6c2'
      white:   '#abb2bf'
    cursor:
      cursor: '#abb2bf'
      text: '#14171c'
# Colors (CyberPunk) Jan Rice
  jan_cyberpunk: &jan_cyberpunk
    primary:
      background: '#070219'
      foreground: '#c0caf5'
    normal:
      black:   '#626483'
      red:     '#fb007a'
      green:   '#a6e22e'
      yellow:  '#f3e430'
      blue:    '#58AFC2'
      magenta: '#583794'
      cyan:    '#926BCA'
      white:   '#d9d9d9'
    bright:
      black:   '#626483'
      red:     '#fb007a'
      green:   '#a6e22e'
      yellow:  '#f3e430'
      blue:    '#58AFC2'
      magenta: '#472575'
      cyan:    '#926BCA'
      white:   '#f1f1f1'
    cursor:
      cursor: '#fb007a'
      text: '#070219'
# Colors (Zombie-Night color scheme) Karla Rice
  karla_z0mbi3_night: &karla_z0mbi3_night
    primary:
      background: '#0E1113'
      foreground: '#afb1db'
    normal:
      black:   '#2d2b36'
      red:     '#e7034a'
      green:   '#61b33e'
      yellow:  '#ffb964'
      blue:    '#5884d4'
      magenta: '#7a44e3'
      cyan:    '#7df0f0'
      white:   '#faf7ff'
    bright:
      black:   '#373542'
      red:     '#e71c5b'
      green:   '#6fb352'
      yellow:  '#ffb964'
      blue:    '#5f90ea'
      magenta: '#8656e3'
      cyan:    '#97f0f0'
      white:   '#fdfcff'
    cursor:
      cursor: '#8656e3'
      text: '#0b0b12'
# Colors (Elenapan) Pamela Rice
  pamela_color_scheme: &pamela_color_scheme
    primary:
      background: '#1D1F28'
      foreground: '#FDFDFD'
    normal:
      black:   '#3D4C5F'
      red:     '#F37F97'
      green:   '#5ADECD'
      yellow:  '#F2A272'
      blue:    '#8897F4'
      magenta: '#C574DD'
      cyan:    '#79E6F3'
      white:   '#FDFDFD'
    bright:
      black:   '#56687E'
      red:     '#FF4971'
      green:   '#18E3C8'
      yellow:  '#FF8037'
      blue:    '#556FFF'
      magenta: '#B043D1'
      cyan:    '#3FDCEE'
      white:   '#BEBEC1'
    cursor:
      cursor: '#FF4971'
      text: '#1D1F28'
# Colors (Gruvbox) Silvia Rice
  silvia_gruvbox: &silvia_gruvbox
    primary:
      background: '#282828'
      foreground: '#fbf1c7'
    normal:
      black:   '#a89984'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#ebdbb2'
    bright:
      black:   '#a89984'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'
    cursor:
      cursor: '#fbf1c7'
      text: '#282828'

# Set the color scheme for the actual rice.
colors: *silvia_gruvbox
