# (Aing) Aing Rice

# Default colors
[colors.primary]
background = "#161a22"
foreground = "#cadee7"

# Cursor colors
[colors.cursor]
cursor = "#cadee7"
text = "#cadee7"

# Normal colors
[colors.normal]
black = "#1e232e"
blue = "#D2ACA9"
cyan = "#99A9CC"
green = "#6E91BA"
magenta = "#E3C4BA"
red = "#927887"
white = "#edf4f7"
yellow = "#A393A2"

# Bright colors
[colors.bright]
black = "#8d9ba1"
blue = "#D2ACA9"
cyan = "#99A9CC"
green = "#6E91BA"
magenta = "#E3C4BA"
red = "#927887"
white = "#cadee7"
yellow = "#A393A2"
