# Default colors
[colors.primary]
background = "#161a22"
foreground = "#cadee7"

# Cursor colors
[colors.cursor]
cursor = "#cadee7"
text = "#161a22"

# Normal colors
[colors.normal]
black = "#1e232e"
red = "#927887"
green = "#6E91BA"
yellow = "#A393A2"
blue = "#D2ACA9"
magenta = "#E3C4BA"
cyan = "#99A9CC"
white = "#edf4f7"

# Bright colors
[colors.bright]
black = "#626483"
red = "#927887"
green = "#6E91BA"
yellow = "#A393A2"
blue = "#D2ACA9"
magenta = "#E3C4BA"
cyan = "#99A9CC"
white = "#cadee7"
