server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "rofi"
preview_length = 80

[rofi]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = ["-theme", ".config/bspwm/src/rofi-themes/Clipboard.rasi"]

[dmenu]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []

[choose]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []

[custom_finder]
program = "fzf"
args = []

[log]
emit_journald = false
emit_stdout = false
emit_stderr = false
level = "INFO"
