#!/usr/bin/env bash
# Author : rxyhn

readonly DIR="$HOME/.config/bspwm/src/assets"
readonly BRIGHTNESS_STEPS=5
readonly MIN_BRIGHTNESS=2

get_brightness() {
    brightnessctl i | awk -F '[()%]' '/Current brightness:/ {print $2}'
}

send_notification() {
    local brightness="$1"
    local icon="$DIR/brightness.svg"
    local bar=""
    local -i bar_length=$((brightness / BRIGHTNESS_STEPS))

    for ((i = 0; i < bar_length; i++)); do
        bar+="─"
    done

    dunstify "Brightness $brightness%" -i "$icon" -r 5555 -u normal \
             -h "int:value:$brightness"
}

adjust_brightness() {
    local -i current
    current="$(get_brightness)"

    case $1 in
        up)
            if ((current == MIN_BRIGHTNESS)); then
                brightnessctl set "${BRIGHTNESS_STEPS}%" -q
            else
                brightnessctl set "${BRIGHTNESS_STEPS}%+" -q
            fi
            ;;
        down)
            if ((current <= MIN_BRIGHTNESS + BRIGHTNESS_STEPS)); then
                brightnessctl set "${MIN_BRIGHTNESS}%" -q
            else
                brightnessctl set "${BRIGHTNESS_STEPS}%-" -q
            fi
            ;;
    esac

    send_notification "$(get_brightness)"
}

case $1 in
    up|down) adjust_brightness "$1" ;;
esac
