#!/usr/bin/env bash
## ╻ ╻╻╺┳┓┏━╸   ┏┓ ┏━┓┏━┓
## ┣━┫┃ ┃┃┣╸    ┣┻┓┣━┫┣┳┛
## ╹ ╹╹╺┻┛┗━╸   ┗━┛╹ ╹╹┗╸ by adilhyz

function hide() {
	
case "${RICETHEME}" in
    jan|silvia|pamela)
        polybar-msg cmd hide | bspc config top_padding 2
        ;;
    aing|esostrefis)
        polybar-msg cmd hide | bspc config bottom_padding 2
        ;;
    siduru)
        polybar-msg cmd hide | bspc config top_padding 2 && bspc config bottom_padding 2
        ;;
    *)
        echo "Error: Something fails dud.."
        ;;
esac
	
}

function unhide() {
	
case "${RICETHEME}" in
	aing)
		polybar-msg cmd show | bspc config bottom_padding 30
		;;
	esostrefis)
		polybar-msg cmd show | bspc config top_padding 0
		;;
	jan)
		polybar-msg cmd show | bspc config top_padding 12
		;;
	pamela)
		polybar-msg cmd show | bspc config top_padding 0
		;;
	siduru)
		polybar-msg cmd show | bspc config top_padding 40 && bspc config bottom_padding 33
		;;
	silvia)
		polybar-msg cmd show | bspc config top_padding 52
		;;
	*)
		echo "Error: Something fails dud.."
		;;
esac

}

case $1 in
	-h | --hide | hide)
		hide
		exit;;
	-u | --unhide | unhide)
		unhide
		exit;;
	*) # Invalid option
		echo "Error: Invalid option"
		exit;;
esac
