#!/usr/bin/env bash
#  ╔═╗╔═╗╔═╗╔═╗  ╦  ╔═╗╦ ╦╔╗╔╔═╗╦ ╦╔═╗╦═╗
#  ╠═╣╠═╝╠═╝╚═╗  ║  ╠═╣║ ║║║║║  ╠═╣║╣ ╠╦╝
#  ╩ ╩╩  ╩  ╚═╝  ╩═╝╩ ╩╚═╝╝╚╝╚═╝╩ ╩╚═╝╩╚═
#	Script to control apps launcher
#   Author: z0mbi3
#	  Modified: me

# From here you can control your favorite applications for all themes.

WIDGET_DIR="$HOME/.config/bspwm/eww"

case "$1" in
  --menu)
    #rofi -show drun -theme $HOME/.config/bspwm/rices/${RICETHEME}/launcher.rasi
    rofi -show drun -theme $HOME/.config/bspwm/src/rofi-themes/Launcher.rasi
    ;;
  --rice)
    RiceSelector
    ;;
  --terminal)
    Term --terminal
    ;;
  --floating)
    Term --floating
    ;;
  --update)
    Term --update 
    ;;
  --checkupdates)
    Term --checkupdates
    ;;
  --clipboard)
    clipcat-menu
    ;;
  --yazi)
    Term --yazi
    ;;
  --nvim)
    Term --nvim
    ;;
  --music)
    Term --music
    ;;
  --fetch)
    Term --fetch
    ;;
  --scratch)
    Bspwm-ScratchPad
    ;;
  --htop)
    Term --htop
    ;;
  #Apps
  --filemanager)
    thunar
    ;;
  --browser)
    firefox
    ;;
  --editor)
    geany
    ;;
  --telegram)
    telegram-desktop
    ;;
  --whats)
    whatsapp-nativefier --disable-gpu
    ;;
  --soundcontrol)
    pavucontrol
    ;;
  --spot)
    spotify
    ;;
  --powermenu)
    PowerMenu
    #eww -c "$WIDGET_DIR" open --toggle powermenu
    ;;
  --keyboard)
    KeyBoardL
    ;;
  # Eww Widgets
  --KeyHelp)
    eww -c "$WIDGET_DIR" open --toggle csheet
    ;;
  --usercard)
    eww -c "$WIDGET_DIR" open --toggle launchermenu
    ;;
  --player)
    eww -c "$WIDGET_DIR" open --toggle music
    ;;
  --calendar)
    eww -c "$WIDGET_DIR" open --toggle date
    ;;
  *)
    echo "Invalid Option"
    ;;
esac
