#!/usr/bin/env bash
## ┏┓ ┏━┓┏━┓╻ ╻┏┳┓
## ┣┻┓┗━┓┣━┛┃╻┃┃┃┃
## ┗━┛┗━┛╹  ┗┻┛╹ ╹ by adilhyz

# Current rice
read -r RICETHEME < "${HOME}"/.config/bspwm/.rice
rice_dir="$HOME/.config/bspwm/rices/$RICETHEME"
export RICETHEME

# Set environment variables
export PATH="$HOME/.config/bspwm/src:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd'

#  ╻ ╻┏━┓┏━┓╻┏ ┏━┓┏━┓┏━┓┏━╸┏━╸┏━┓
#  ┃╻┃┃ ┃┣┳┛┣┻┓┗━┓┣━┛┣━┫┃  ┣╸ ┗━┓
#  ┗┻┛┗━┛╹┗╸╹ ╹┗━┛╹  ╹ ╹┗━╸┗━╸┗━┛

MonitorSetup

#  ┏┓ ┏━┓┏━┓╻ ╻┏┳┓   ┏━╸┏━┓┏┓╻┏━╸╻┏━╸
#  ┣┻┓┗━┓┣━┛┃╻┃┃┃┃   ┃  ┃ ┃┃┗┫┣╸ ┃┃╺┓
#  ┗━┛┗━┛╹  ┗┻┛╹ ╹   ┗━╸┗━┛╹ ╹╹  ╹┗━┛

#bspc config external_rules_command $HOME/.config/bspwm/src/ExternalRules

bspc config window_gap                  6
bspc config split_ratio                 0.51
bspc config single_monocle              true
bspc config borderless_monocle          false
bspc config gapless_monocle             false

bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       false
bspc config pointer_motion_interval     5
bspc config pointer_modifier            mod4 
bspc config pointer_action1             move 
bspc config pointer_action2             resize_side 
bspc config pointer_action3             resize_corner

#  ┏━┓╻ ╻╻  ┏━╸┏━┓
#  ┣┳┛┃ ┃┃  ┣╸ ┗━┓
#  ╹┗╸┗━┛┗━╸┗━╸┗━┛

# remove all rules first
bspc rule -r *:*

#bspc wm --adopt-orphans
bspc rule -a scratch sticky=on state=floating focus=on
bspc rule -a Subl desktop='^4' follow=on
bspc rule -a brave desktop='^2' follow=on
bspc rule -a google-chrome-stable desktop='^2' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a waterfox desktop='^2' follow=on
bspc rule -a discord desktop='^6' follow=on
bspc rule -a Spotify desktop='^5' follow=on
bspc rule -a whatsdesk desktop='^5' follow=on
bspc rule -a TelegramDesktop desktop='^5' follow=on
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
bspc rule -a Virt-manager state=fullscreen
bspc rule -a inkscape state=fullscreen
bspc rule -a Arandr state=floating
bspc rule -a Galculator state=floating
bspc rule -a Oblogout state=floating
bspc rule -a Xfce4-terminal state=floating
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a Sysfetch state=floating center=on rectangle=370x700+0+0
bspc rule -a FloaTerm state=floating center=on 
bspc rule -a Updating state=floating sticky=on center=on
bspc rule -a mpv state=floating layer=below
bspc rule -a xwinwrap state=floating layer=below

## ┏━┓╻ ╻╺┳╸┏━┓┏━┓╺┳╸┏━┓┏━┓╺┳╸
## ┣━┫┃ ┃ ┃ ┃ ┃┗━┓ ┃ ┣━┫┣┳┛ ┃ 
## ╹ ╹┗━┛ ╹ ┗━┛┗━┛ ╹ ╹ ╹╹┗╸ ╹ 

run() {
  if ! pidof -q "$1"; then
    "$@" &
  fi
}

# Set system vars for polybar
"$HOME"/.config/bspwm/src/SetSysVars

# Terminate already running polybar, stalonetray, sxhkd and dunst instances
processes=("sxhkd" "polybar" "dunst" "eww.*bar" "stalonetray")

for process in "${processes[@]}"; do
    if pgrep -f "$process"; then
        pkill -f "$process" > /dev/null; sleep 0.25
    fi
done

# Launch sxhkd daemon
run sxhkd -c "${HOME}"/.config/bspwm/src/config/sxhkdrc

# Launch picom
run picom --config "${HOME}"/.config/bspwm/src/config/picom.conf

# Load current theme
"${HOME}"/.config/bspwm/src/Theme.sh

# Lauch xsettingsd daemon
run xsettingsd --config="${HOME}"/.config/bspwm/src/config/xsettingsd >/dev/null 2>&1

# Launch eww daemon
pidof -q eww || { eww -c "$HOME"/.config/bspwm/eww daemon & }

# Launch clipboard daemon
pidof -q clipcatd || { clipcatd & }

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Launch dunst notification daemon
dunst -config "$HOME"/.config/bspwm/src/config/dunstrc &

# Launch stalonetray
stalonetray -c "$HOME"/.config/bspwm/src/config/stalonetrayrc & sleep 0.01 && xdo hide -N stalonetray && touch "/tmp/syshide.lock"

# Teuingg
numlockx on &

# Internet
nm-applet &

# Bluetooth
blueberry-tray &

# Auto Lock
xautolock -detectsleep -time 5 -locker ScreenLocker &

# Typing repeat speed
#xset r rate 375 45 &

# End one time code