#!/usr/bin/env bash
##  ┏┓┏━┓┏┓╻   ┏━┓╻┏━╸┏━╸
##   ┃┣━┫┃┗┫   ┣┳┛┃┃  ┣╸ 
## ┗━┛╹ ╹╹ ╹   ╹┗╸╹┗━╸┗━╸ by adilhyz
## This file will configure the options
## and launch the bars corresponding to each theme.

# Current Rice
read -r RICE < "$HOME"/.config/bspwm/.rice

# Terminate or reload existing processes if necessary.
. "${HOME}"/.config/bspwm/src/Process.bash

# Vars config for Jan Rice
# Bspwm border  # Top pad  # Bottom pad   # Normal border color # Active border color  # Focused border color  # Presel border colos  # Left pad   # Right pad  # Window gap
BORDER_WIDTH="0"  TP="-2"   BP="-2"        NORMAL_BC="#4C3A6D"   ACTIVE_BC="#4C3A6D"    FOCUSED_BC="#785DA5"   	PRESEL_BC="#070219"    LP="-2"       RP="-2"       WG="12"

# Fade true|false	# Shadows true|false	# Corner radius		# Shadow color			# Animations true|false
P_FADE="false"		P_SHADOWS="false"		P_CORNER_R="0"		SHADOW_C="#000000"		ANIMATIONS="false"

## Theme
BDIR="$HOME/.config/bspwm"
TDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
THEME="${TDIR##*/}"

# Set bspwm configuration
set_bspwm_config() {
	bspc config border_width ${BORDER_WIDTH}
	bspc config top_padding ${TP}
	bspc config bottom_padding ${BP}
	bspc config normal_border_color ${NORMAL_BC}
	bspc config active_border_color ${ACTIVE_BC}
	bspc config focused_border_color ${FOCUSED_BC}
	bspc config presel_feedback_color ${PRESEL_BC}
	bspc config left_padding ${LP}
	bspc config right_padding ${RP}
	bspc config window_gap ${WG}
}

# Reload terminal colors
set_alacritty_config() {
cat > "$HOME"/.config/alacritty/rice-colors.toml << EOF
# (CyberPunk) Color scheme for Jan Rice
# Default colors
[colors.primary]
background = "#070219"
foreground = "#c0caf5"
# Cursor colors
[colors.cursor]
cursor = "#fb007a"
text = "#070219"
# Normal colors
[colors.normal]
black = "#626483"
blue = "#19bffe"
cyan = "#43fbff"
green = "#a6e22e"
magenta = "#6800d2"
red = "#fb007a"
white = "#d9d9d9"
yellow = "#f3e430"
# Bright colors
[colors.bright]
black = "#626483"
blue = "#19bffe"
cyan = "#43fbff"
green = "#a6e22e"
magenta = "#472575"
red = "#fb007a"
white = "#f1f1f1"
yellow = "#f3e430"
EOF
}

# Set kitty colorscheme
set_kitty_config() {
  cat >"$HOME"/.config/kitty/current-theme.conf <<EOF
## This file is autogenerated, do not edit it, instead edit the Theme.sh file inside the rice directory.
## (CyberPunk) Color scheme for Jan Rice


# The basic colors
foreground              #c0caf5
background              #070219
selection_foreground    #070219
selection_background    #c0caf5

# Cursor colors
cursor                  #fb007a
cursor_text_color       #070219

# URL underline color when hovering with mouse
url_color               #19bffe

# Kitty window border colors
active_border_color     #c0caf5
inactive_border_color   #6800d2
bell_border_color       #f3e430

# Tab bar colors
active_tab_foreground   #c0caf5
active_tab_background   #6800d2
inactive_tab_foreground #070219
inactive_tab_background #626483
tab_bar_background      #070219

# The 16 terminal colors

# black
color0 #626483
color8 #626483

# red
color1 #fb007a
color9 #fb007a

# green
color2  #a6e22e
color10 #a6e22e

# yellow
color3  #f3e430
color11 #f3e430

# blue
color4  #19bffe
color12 #58AFC2

# magenta
color5  #6800d2
color13 #472575

# cyan
color6  #43fbff
color14 #926BCA

# white
color7  #d9d9d9
color15 #f1f1f1
EOF

killall -USR1 kitty
}

# Set compositor configuration
set_picom_config() {
  picom_conf_file="$HOME/.config/bspwm/src/config/picom.conf"
  picom_rules_file="$HOME/.config/bspwm/src/config/picom-rules.conf"

  sed -i "$picom_conf_file" \
    -e "s/shadow = .*/shadow = ${P_SHADOWS};/" \
    -e "s/shadow-color = .*/shadow-color = \"${SHADOW_C}\"/" \
    -e "s/fading = .*/fading = ${P_FADE};/" \
    -e "s/corner-radius = .*/corner-radius = ${P_CORNER_R}/"

  sed -i "$picom_rules_file" \
    -e "95s/  opacity = .*/ opacity = 0.96;/"

  if [[ "$ANIMATIONS" = "true" ]]; then
    sed -i "$picom_rules_file" \
      -e '/picom-animations/c\@include "picom-animations.conf"'
  else
    sed -i "$picom_rules_file" \
      -e '/picom-animations/c\#@include "picom-animations.conf"'
  fi
}

# Set stalonetray config
set_stalonetray_config() {
	sed -i "$HOME"/.config/bspwm/stalonetrayrc \
		-e "s/background .*/background \"#070219\"/" \
		-e "s/vertical .*/vertical true/" \
		-e "s/geometry .*/geometry 1x1-133+57/" \
		-e "s/grow_gravity .*/grow_gravity NE/" \
		-e "s/icon_gravity .*/icon_gravity NE/"
}

# Set dunst notification daemon config
set_dunst_config() {
	sed -i "$HOME"/.config/bspwm/dunstrc \
		-e "s/transparency = .*/transparency = 8/g" \
		-e "s/frame_color = .*/frame_color = \"#6800d2\"/g" \
		-e "s/frame_width = .*/frame_width = \"1\"/g" \
		-e "s/separator_color = .*/separator_color = \"#fb007a\"/g" \
		-e "s/font = .*/font = JetBrainsMono NF Medium 9/g" \
		-e "s/foreground='.*'/foreground='#f9f9f9'/g" \
		-e "s/origin = .*/origin = top-right/g" \
		-e "s/offset = .*/offset = 10x56/g" \
		-e "s/icon_position = .*/icon_position = left/g" \
		-e "s/max_icon_size = .*/max_icon_size = 50/g" \
		-e "s/corner_radius = .*/corner_radius = 0/g"
	
	sed -i '/urgency_low/Q' "$HOME"/.config/bspwm/dunstrc
	cat >> "$HOME"/.config/bspwm/dunstrc <<- _EOF_
		[urgency_low]
		timeout = 3
		background = "#070219"
		foreground = "#c0caf5"

		[urgency_normal]
		timeout = 6
		background = "#070219"
		foreground = "#c0caf5"

		[urgency_critical]
		timeout = 0
		background = "#070219"
		foreground = "#c0caf5"
_EOF_
}

# Set eww colors
set_eww_colors() {
	cat > "$HOME"/.config/bspwm/eww/colors.scss << EOF
// Eww colors for Jan rice
\$bg: #070219;
\$bg-alt: #09021f;
\$fg: #c0caf5;
\$black: #626483;
\$lightblack: #262831;
\$red: #fb007a;
\$blue: #19bffe;
\$cyan: #43fbff;
\$magenta: #6800d2;
\$green: #a6e22e;
\$yellow: #f3e430;
\$archicon: #0f94d2;
EOF
}

# Set jgmenu colors for Jan
set_jgmenu_colors() {
	sed -i "$HOME"/.config/bspwm/jgmenurc \
		-e 's/color_menu_bg = .*/color_menu_bg = #070219/' \
		-e 's/color_norm_fg = .*/color_norm_fg = #c0caf5/' \
		-e 's/color_sel_bg = .*/color_sel_bg = #09021f/' \
		-e 's/color_sel_fg = .*/color_sel_fg = #c0caf5/' \
		-e 's/color_sep_fg = .*/color_sep_fg = #626483/'
}

# Set Rofi launcher config
set_launcher_config () {
cat >"$HOME"/.config/bspwm/src/rofi-themes/shared.rasi <<EOF
// Rofi colors for Jan
* {
    font: "Terminess Nerd Font Mono Bold 10";
    background: #070219;
    background-alt: #070219F0;
    foreground: #c0caf5;
    selected: #fb007af0;
    active: #4C3A6D;
    urgent: #fb007a;
    img-background: url("~/.config/bspwm/rices/jan/rofi.webp", width);
    main-bg: #070219F0;
    main-fg: #c0caf5;
    main-fg-alt: #070219F0;
    select-bg: #fb007a;
    select-fg: #070219;
}

EOF

sed -i "$HOME/.config/bspwm/src/rofi-themes/Window.rasi" \
    -e '17s|\(font:\s*\).*|\1"Terminess Nerd Font Mono Bold 10";|' \
    -e 's|\(font-weight:\s*\).*|\1bold;|' \
    -e 's|\(background:\s*\).*|\1#070219;|' \
    -e 's|\(background-alt:\s*\).*|\1#070219F0;|' \
    -e 's|\(foreground:\s*\).*|\1#00c9fe;|' \
    -e 's|\(selected:\s*\).*|\1#6800d2;|' \
    -e 's|\(highlight:\s*\).*|\1#BE00CD;|' \
    -e 's|\(urgent:\s*\).*|\1#f4155a;|' \
    -e 's|\(window-format:\s*\).*|\1"{c}  {w}  {t}";|' \
    -e '25s|\(on:\s*\).*|\1#8df202;|' \
    -e '26s|\(off:\s*\).*|\1#f4155a;|' \
    -e '60s|\(background-color:\s*\).*|\1@selected;|' \
    -e '61s|\(text-color:\s*\).*|\1@foreground;|' \
    -e '67s|\(background-color:\s*\).*|\1@selected;|' \
    -e '68s|\(text-color:\s*\).*|\1@foreground;|' \
    -e '72s|\(border-color:\s*\).*|\1@selected;|' \
    -e 's|\(background-image:.*rices/\)[^/]*|\1jan|'
}

# Appearance
set_appearance() {
	XFILE="$BDIR/xsettingsd"
	GTK2FILE="$HOME/.gtkrc-2.0"
	GTK3FILE="$HOME/.config/gtk-3.0/settings.ini"

	# apply gtk theme, icons, cursor & fonts
	if [[ `pidof xsettingsd` ]]; then
		sed -i -e "s|Net/ThemeName .*|Net/ThemeName \"Cyberpunk\"|g" ${XFILE}
		sed -i -e "s|Net/IconThemeName .*|Net/IconThemeName \"Win11-Dark\"|g" ${XFILE}
		sed -i -e "s|Gtk/CursorThemeName .*|Gtk/CursorThemeName \"capitaine-cursors\"|g" ${XFILE}
	else
		sed -i -e "s/gtk-font-name=.*/gtk-font-name=\"Noto Sans 9\"/g" ${GTK2FILE}
		sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=\"Cyberpunk\"/g" ${GTK2FILE}
		sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=\"Win11-Dark\"/g" ${GTK2FILE}
		sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=\"capitaine-cursors\"/g" ${GTK2FILE}
		
		sed -i -e "s/gtk-font-name=.*/gtk-font-name=Noto Sans 9/g" ${GTK3FILE}
		sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=Cyberpunk/g" ${GTK3FILE}
		sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Win11-Dark/g" ${GTK3FILE}
		sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=capitaine-cursors/g" ${GTK3FILE}
	fi
	
	# inherit cursor theme
	if [[ -f "$HOME"/.icons/default/index.theme ]]; then
		sed -i -e "s/Inherits=.*/Inherits=capitaine-cursors/g" "$HOME"/.icons/default/index.theme
	fi	
}

# Set color cava
set_cava() {
	sed -i "$HOME/.config/cava/config" \
		-e "s/foreground = .*/foreground = magenta/g"
}

# Launch the bar
launch_bars() {
	for mon in $(polybar --list-monitors | cut -d":" -f1); do
		MONITOR=$mon polybar -q main -c ${rice_dir}/config.ini &
	done
}


### ---------- Apply Configurations ---------- ###

set_bspwm_config
set_alacritty_config
set_kitty_config
set_picom_config
set_stalonetray_config
launch_bars
set_dunst_config
set_eww_colors
set_jgmenu_colors
set_launcher_config
set_cava
set_appearance