#!/usr/bin/env bash
## ┏━┓╻╻  ╻ ╻╻┏━┓   ┏━┓╻┏━╸┏━╸
## ┗━┓┃┃  ┃┏┛┃┣━┫   ┣┳┛┃┃  ┣╸ 
## ┗━┛╹┗━╸┗┛ ╹╹ ╹   ╹┗╸╹┗━╸┗━╸ by adilhyz
## This file will configure the options
## and launch the bars corresponding to each theme.

# Current Rice
read -r RICE < "$HOME"/.config/bspwm/.rice

# Terminate or reload existing processes if necessary.
. "${HOME}"/.config/bspwm/src/Process.bash

# Vars config for Siduru Rice
# Bspwm border  # Top pad  # Bottom pad   # Normal border color # Active border color  # Focused border color  # Presel border colos  # Left pad   # Right pad  # Window gap
BORDER_WIDTH="0"  TP="36"   BP="2"        NORMAL_BC="#d3869b"   ACTIVE_BC="#d3869b"    FOCUSED_BC="#fbf1c7"   	PRESEL_BC="#b8bb26"    LP="2"       RP="2"       WG="6"

# Fade true|false	# Shadows true|false	# Corner radius		# Shadow color			# Animations true|false
P_FADE="true"		P_SHADOWS="true"		P_CORNER_R="6"		SHADOW_C="#000000"		ANIMATIONS="true"

## Theme
BDIR="$HOME/.config/bspwm"
TDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
THEME="${TDIR##*/}"

# Set bspwm configuration
set_bspwm_config() {
	bspc config border_width ${BORDER_WIDTH}
	bspc config top_padding ${TP}
	bspc config bottom_padding ${BP}
	bspc config normal_border_color ${NORMAL_BC}
	bspc config active_border_color ${ACTIVE_BC}
	bspc config focused_border_color ${FOCUSED_BC}
	bspc config presel_feedback_color ${PRESEL_BC}
	bspc config left_padding ${LP}
	bspc config right_padding ${RP}
	bspc config window_gap ${WG}
}

# Reload terminal colors
set_alacritty_config() {
cat > "$HOME"/.config/alacritty/rice-colors.toml << EOF
# (Gruvbox) Color scheme for Silvia Rice
# Default colors
[colors.primary]
background = "#282828"
foreground = "#fbf1c7"
# Cursor colors
[colors.cursor]
cursor = "#fbf1c7"
text = "#282828"
# Normal colors
[colors.normal]
black = "#a89984"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#ebdbb2"
yellow = "#d79921"
# Bright colors
[colors.bright]
black = "#a89984"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"
EOF
}

# Set kitty colorscheme
set_kitty_config() {
  cat >"$HOME"/.config/kitty/current-theme.conf <<EOF
## This file is autogenerated, do not edit it, instead edit the Theme.sh file inside the rice directory.
## # (Gruvbox) Color scheme for Silvia Rice


# The basic colors
foreground              #fbf1c7
background              #282828
selection_foreground    #282828
selection_background    #fabd2f

# Cursor colors
cursor                  #fbf1c7
cursor_text_color       #282828

# URL underline color when hovering with mouse
url_color               #83a598

# Kitty window border colors
active_border_color     #d3869b
inactive_border_color   #a89984
bell_border_color       #fabd2f

# Tab bar colors
active_tab_foreground   #282828
active_tab_background   #d3869b
inactive_tab_foreground #fbf1c7
inactive_tab_background #a89984
tab_bar_background      #282828

# The 16 terminal colors

# black
color0 #a89984
color8 #a89984

# red
color1 #cc241d
color9 #fb4934

# green
color2  #98971a
color10 #b8bb26

# yellow
color3  #d79921
color11 #fabd2f

# blue
color4  #458588
color12 #83a598

# magenta
color5  #b16286
color13 #d3869b

# cyan
color6  #689d6a
color14 #8ec07c

# white
color7  #ebdbb2
color15 #ebdbb2
EOF

killall -USR1 kitty
}

# Set compositor configuration
set_picom_config() {
  picom_conf_file="$HOME/.config/bspwm/src/config/picom.conf"
  picom_rules_file="$HOME/.config/bspwm/src/config/picom-rules.conf"

  sed -i "$picom_conf_file" \
    -e "s/shadow = .*/shadow = ${P_SHADOWS};/" \
    -e "s/shadow-color = .*/shadow-color = \"${SHADOW_C}\"/" \
    -e "s/fading = .*/fading = ${P_FADE};/" \
    -e "s/corner-radius = .*/corner-radius = ${P_CORNER_R}/"

  sed -i "$picom_rules_file" \
    -e "95s/  opacity = .*/ opacity = 0.96;/"

  if [[ "$ANIMATIONS" = "true" ]]; then
    sed -i "$picom_rules_file" \
      -e '/picom-animations/c\@include "picom-animations.conf"'
  else
    sed -i "$picom_rules_file" \
      -e '/picom-animations/c\#@include "picom-animations.conf"'
  fi
}

# Set stalonetray config
set_stalonetray_config() {
	sed -i "$HOME"/.config/bspwm/stalonetrayrc \
		-e "s/background .*/background \"#3C3836\"/" \
		-e "s/vertical .*/vertical true/" \
		-e "s/geometry .*/geometry 1x1-6+45/" \
		-e "s/grow_gravity .*/grow_gravity NE/" \
		-e "s/icon_gravity .*/icon_gravity NE/"
}

# Set dunst notification daemon config
set_dunst_config() {
	sed -i "$HOME"/.config/bspwm/dunstrc \
		-e "s/transparency = .*/transparency = 0/g" \
		-e "s/frame_color = .*/frame_color = \"#282828\"/g" \
		-e "s/separator_color = .*/separator_color = \"#d3869b\"/g" \
		-e "s/font = .*/font = JetBrainsMono NF Medium 9/g" \
		-e "s/foreground='.*'/foreground='#d3869b'/g" \
		-e "s/origin = .*/origin = top-right/g" \
		-e "s/offset = .*/offset = 8x42/g" \
		-e "s/icon_position = .*/icon_position = left/g" \
		-e "s/max_icon_size = .*/max_icon_size = 50/g" \
		-e "s/corner_radius = .*/corner_radius = 0/g"
		
	sed -i '/urgency_low/Q' "$HOME"/.config/bspwm/dunstrc
	cat >> "$HOME"/.config/bspwm/dunstrc <<- _EOF_
			[urgency_low]
			timeout = 3
			background = "#282828"
			foreground = "#fbf1c7"

			[urgency_normal]
			timeout = 6
			background = "#282828"
			foreground = "#fbf1c7"

			[urgency_critical]
			timeout = 0
			background = "#282828"
			foreground = "#fbf1c7"
_EOF_
}

# Set eww colors
set_eww_colors() {
	cat > "$HOME"/.config/bspwm/eww/colors.scss << EOF
// Eww colors for Silvia rice
\$bg: #282828;
\$bg-alt: #2E2E2E;
\$fg: #fbf1c7;
\$black: #a89984;
\$lightblack: #262831;
\$red: #fb4934;
\$blue: #83a598;
\$cyan: #8ec07c;
\$magenta: #d3869b;
\$green: #b8bb26;
\$yellow: #fabd2f;
\$archicon: #0f94d2;
EOF
}

# Set jgmenu colors for Silvia
set_jgmenu_colors() {
	sed -i "$HOME"/.config/bspwm/jgmenurc \
		-e 's/color_menu_bg = .*/color_menu_bg = #282828/' \
		-e 's/color_norm_fg = .*/color_norm_fg = #fbf1c7/' \
		-e 's/color_sel_bg = .*/color_sel_bg = #2E2E2E/' \
		-e 's/color_sel_fg = .*/color_sel_fg = #fbf1c7/' \
		-e 's/color_sep_fg = .*/color_sep_fg = #a89984/'
}

# Appearance
set_appearance() {
	XFILE="$BDIR/xsettingsd"
	GTK2FILE="$HOME/.gtkrc-2.0"
	GTK3FILE="$HOME/.config/gtk-3.0/settings.ini"

	# apply gtk theme, icons, cursor & fonts
	if [[ `pidof xsettingsd` ]]; then
		sed -i -e "s|Net/ThemeName .*|Net/ThemeName \"Gruvbox\"|g" ${XFILE}
		sed -i -e "s|Net/IconThemeName .*|Net/IconThemeName \"Nordzy-pink-dark\"|g" ${XFILE}
		sed -i -e "s|Gtk/CursorThemeName .*|Gtk/CursorThemeName \"phinger-cursors\"|g" ${XFILE}
	else
		sed -i -e "s/gtk-font-name=.*/gtk-font-name=\"Noto Sans 9\"/g" ${GTK2FILE}
		sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=\"Gruvbox\"/g" ${GTK2FILE}
		sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=\"Nordzy-pink-dark\"/g" ${GTK2FILE}
		sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=\"phinger-cursors\"/g" ${GTK2FILE}
		
		sed -i -e "s/gtk-font-name=.*/gtk-font-name=Noto Sans 9/g" ${GTK3FILE}
		sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=Gruvbox/g" ${GTK3FILE}
		sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Nordzy-pink-dark/g" ${GTK3FILE}
		sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=phinger-cursors/g" ${GTK3FILE}
	fi
	
	# inherit cursor theme
	if [[ -f "$HOME"/.icons/default/index.theme ]]; then
		sed -i -e "s/Inherits=.*/Inherits=phinger-cursors/g" "$HOME"/.icons/default/index.theme
	fi	
}

# Set Rofi launcher config
set_launcher_config () {
	cat >"$HOME"/.config/bspwm/src/rofi-themes/shared.rasi <<EOF
// Rofi colors for Silvia
* {
    font: "scientifica 12";
    background: #282828;
    background-alt: #282828E0;
    foreground: #fbf1c7;
    selected: #d79921;
    active: #d3869b;
    urgent: #fb4934;
    img-background: url("~/.config/bspwm/rices/silvia/rofi.webp", width);
    main-bg: #282828E6;
    main-fg: #fbf1c7;
    main-fg-alt: #282828E6;
    select-bg: #d79921;
    select-fg: #282828;
}
EOF

sed -i "$HOME/.config/bspwm/src/rofi-themes/Window.rasi" \
    -e '17s|\(font:\s*\).*|\1"scientifica 12";|' \
    -e 's|\(font-weight:\s*\).*|\1bold;|' \
    -e 's|\(background:\s*\).*|\1#282828;|' \
    -e 's|\(background-alt:\s*\).*|\1#282828E0;|' \
    -e 's|\(foreground:\s*\).*|\1#fbf1c7;|' \
    -e 's|\(selected:\s*\).*|\1#ebdbb2;|' \
    -e 's|\(highlight:\s*\).*|\1#d79921;|' \
    -e 's|\(urgent:\s*\).*|\1#928374;|' \
    -e 's|\(window-format:\s*\).*|\1"󰇙  {c}   {w} 󰇙 {t}";|' \
    -e '25s|\(on:\s*\).*|\1#98971a;|' \
    -e '26s|\(off:\s*\).*|\1#689d6a;|' \
    -e '60s|\(background-color:\s*\).*|\1@background-alt;|' \
    -e '61s|\(text-color:\s*\).*|\1@foreground;|' \
    -e '67s|\(background-color:\s*\).*|\1@background-alt;|' \
    -e '68s|\(text-color:\s*\).*|\1@highlight;|' \
    -e '72s|\(border-color:\s*\).*|\1@background-alt;|' \
    -e 's|\(background-image:.*rices/\)[^/]*|\1silvia|'
}

# sed -i "$HOME/.config/bspwm/src/Launcher.rasi" \
# 	-e '22s/\(font: \).*/\1"scientifica 12";/' \
# 	-e 's/\(background: \).*/\1#282828;/' \
# 	-e 's/\(background-alt: \).*/\1#282828E0;/' \
# 	-e 's/\(foreground: \).*/\1#fbf1c7;/' \
# 	-e 's/\(selected: \).*/\1#d79921;/' \
# 	-e 's/[^/]*-rofi/si-rofi/'

# # WallSelect menu colors	
# sed -i "$HOME/.config/bspwm/src/WallSelect.rasi" \
# 	-e 's/\(main-bg: \).*/\1#282828E6;/' \
# 	-e 's/\(main-fg: \).*/\1#fbf1c7;/' \
# 	-e 's/\(select-bg: \).*/\1#d79921;/' \
# 	-e 's/\(select-fg: \).*/\1#282828;/'

# Set color cava
set_cava() {
	sed -i "$HOME/.config/cava/config" \
		-e "s/foreground = .*/foreground = magenta/g"
}

# Launch the bar
launch_bars() {

	for mon in $(polybar --list-monitors | cut -d":" -f1); do
		MONITOR=$mon polybar -q cata-bar -c ${rice_dir}/config.ini &
	done

}



### ---------- Apply Configurations ---------- ###

set_bspwm_config
set_alacritty_config
set_kitty_config
set_picom_config
set_stalonetray_config
launch_bars
set_dunst_config
set_eww_colors
set_jgmenu_colors
set_launcher_config
set_cava
set_appearance