#!/usr/bin/env bash
#!/usr/bin/env bash
## ┏━┓╻┏┓╻┏━╸   ┏━┓╻┏━╸┏━╸
## ┣━┫┃┃┗┫┃╺┓   ┣┳┛┃┃  ┣╸ 
## ╹ ╹╹╹ ╹┗━┛   ╹┗╸╹┗━╸┗━╸ by adilhyz
## This file will configure the options
## and launch the bars corresponding to each theme.

# Current Rice
read -r RICE < "$HOME"/.config/bspwm/.rice

# Terminate or reload existing processes if necessary.
. "${HOME}"/.config/bspwm/src/Process.bash

# Vars config for Aing Rice
# Bspwm border  # Top pad  # Bottom pad   # Normal border color # Active border color  # Focused border color  # Presel border colos  # Left pad   # Right pad  # Window gap
BORDER_WIDTH="0"  TP="2"   BP="30"        NORMAL_BC="#6E91BA"   ACTIVE_BC="#6E91BA"    FOCUSED_BC="#E3C4BA"   PRESEL_BC="#E3C4BA"    LP="2"       RP="2"       WG="6"
 
# Fade true|false # Shadows true|false  # Corner radius   # Shadow color      # Animations true|false
P_FADE="true"   P_SHADOWS="false"   P_CORNER_R="0"    SHADOW_C="#000000"    ANIMATIONS="true"

## Theme
BDIR="$HOME/.config/bspwm"
TDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
THEME="${TDIR##*/}"

# Set bspwm configuration
set_bspwm_config() {
	bspc config border_width ${BORDER_WIDTH}
	bspc config top_padding ${TP}
	bspc config bottom_padding ${BP}
	bspc config normal_border_color ${NORMAL_BC}
	bspc config active_border_color ${ACTIVE_BC}
	bspc config focused_border_color ${FOCUSED_BC}
	bspc config presel_feedback_color ${PRESEL_BC}
	bspc config left_padding ${LP}
	bspc config right_padding ${RP}
	bspc config window_gap ${WG}
}

# Reload terminal colors
set_alacritty_config() {
  cat > "$HOME"/.config/alacritty/rice-colors.toml << EOF
# (Aing) Aing Rice

# Default colors
[colors.primary]
background = "#161a22"
foreground = "#cadee7"

# Cursor colors
[colors.cursor]
cursor = "#cadee7"
text = "#cadee7"

# Normal colors
[colors.normal]
black = "#1e232e"
blue = "#D2ACA9"
cyan = "#99A9CC"
green = "#6E91BA"
magenta = "#E3C4BA"
red = "#927887"
white = "#edf4f7"
yellow = "#A393A2"

# Bright colors
[colors.bright]
black = "#8d9ba1"
blue = "#D2ACA9"
cyan = "#99A9CC"
green = "#6E91BA"
magenta = "#E3C4BA"
red = "#927887"
white = "#cadee7"
yellow = "#A393A2"
EOF
}

# Set kitty colorscheme
set_kitty_config() {
  cat >"$HOME"/.config/kitty/current-theme.conf <<EOF
## This file is autogenerated, do not edit it, instead edit the Theme.sh file inside the rice directory.
## (Rose-Pine Moon) Color scheme for Cristina Rice


# The basic colors
foreground              #cadee7
background              #161a22
selection_foreground    #161a22
selection_background    #eabbb9

# Cursor colors
cursor                  #cadee7
cursor_text_color       #161a22

# URL underline color when hovering with mouse
url_color               #D2ACA9

# Kitty window border colors
active_border_color     #cadee7
inactive_border_color   #8d9ba1
bell_border_color       #A393A2

# Tab bar colors
active_tab_foreground   #161a22
active_tab_background   #cadee7
inactive_tab_foreground #cadee7
inactive_tab_background #1e232e
tab_bar_background      #161a22

# The 16 terminal colors

# black
color0 #1e232e
color8 #8d9ba1

# red
color1 #927887
color9 #927887

# green
color2  #6E91BA
color10 #6E91BA

# yellow
color3  #A393A2
color11 #A393A2

# blue
color4  #D2ACA9
color12 #D2ACA9

# magenta
color5  #E3C4BA
color13 #E3C4BA

# cyan
color6  #99A9CC
color14 #99A9CC

# white
color7  #edf4f7
color15 #cadee7
EOF

killall -USR1 kitty
}

# Set compositor configuration
set_picom_config() {
  picom_conf_file="$HOME/.config/bspwm/src/config/picom.conf"
  picom_rules_file="$HOME/.config/bspwm/src/config/picom-rules.conf"

  sed -i "$picom_conf_file" \
    -e "s/shadow = .*/shadow = ${P_SHADOWS};/" \
    -e "s/shadow-color = .*/shadow-color = \"${SHADOW_C}\"/" \
    -e "s/fading = .*/fading = ${P_FADE};/" \
    -e "s/corner-radius = .*/corner-radius = ${P_CORNER_R}/"

  sed -i "$picom_rules_file" \
    -e "95s/  opacity = .*/ opacity = 0.96;/"

  if [[ "$ANIMATIONS" = "true" ]]; then
    sed -i "$picom_rules_file" \
      -e '/picom-animations/c\@include "picom-animations.conf"'
  else
    sed -i "$picom_rules_file" \
      -e '/picom-animations/c\#@include "picom-animations.conf"'
  fi
}


# Set stalonetray config
set_stalonetray_config() {
  sed -i "$HOME"/.config/bspwm/stalonetrayrc \
    -e "s/background .*/background \"#161a22\"/" \
    -e "s/vertical .*/vertical true/" \
    -e "s/geometry .*/geometry 1x1-36+705/" \
    -e "s/grow_gravity .*/grow_gravity SE/" \
    -e "s/icon_gravity .*/icon_gravity SE/"
}

# Set dunst notification daemon config
set_dunst_config() {
	sed -i "$HOME"/.config/bspwm/dunstrc \
    -e "s/transparency = .*/transparency = 0/g" \
    -e "s/frame_color = .*/frame_color = \"#161a22\"/g" \
    -e "s/separator_color = .*/separator_color = \"#927887\"/g" \
    -e "s/font = .*/font = JetBrainsMono NF Medium 9/g" \
    -e "s/foreground='.*'/foreground='#6E91BA'/g" \
    -e "s/origin = .*/origin = bottom-right/g" \
    -e "s/offset = .*/offset = 8x36/g" \
    -e "s/icon_position = .*/icon_position = left/g" \
    -e "s/max_icon_size = .*/max_icon_size = 50/g" \
    -e "s/corner_radius = .*/corner_radius = 0/g"

  
  sed -i '/urgency_low/Q' "$HOME"/.config/bspwm/dunstrc
  cat >> "$HOME"/.config/bspwm/dunstrc <<- _EOF_
    [urgency_low]
    timeout = 3
    background = "#161a22"
    foreground = "#cadee7"

    [urgency_normal]
    timeout = 6
    background = "#161a22"
    foreground = "#cadee7"

    [urgency_critical]
    timeout = 0
    background = "#161a22"
    foreground = "#cadee7"
_EOF_
}

# Set eww colors
set_eww_colors() {
  cat > "$HOME"/.config/bspwm/eww/colors.scss << EOF
// Eww colors for Aing rice
\$bg: #161a22;
\$bg-alt: #262c3a;
\$fg: #cadee7;
\$black: #1e232e;
\$lightblack: #2d3546;
\$red: #927887;
\$blue: #D2ACA9;
\$cyan: #99A9CC;
\$magenta: #E3C4BA;
\$green: #6E91BA;
\$yellow: #A393A2;
\$archicon: #667eb3;
EOF
}

# Set jgmenu colors for Aing
set_jgmenu_colors() {
  sed -i "$HOME"/.config/bspwm/jgmenurc \
    -e 's/color_menu_bg = .*/color_menu_bg = #161a22/' \
    -e 's/color_norm_fg = .*/color_norm_fg = #cadee7/' \
    -e 's/color_sel_bg = .*/color_sel_bg = #262c3a/' \
    -e 's/color_sel_fg = .*/color_sel_fg = #cadee7/' \
    -e 's/color_sep_fg = .*/color_sep_fg = #1e232e/'
}

# Set Rofi launcher config
set_launcher_config () {
  cat >"$HOME"/.config/bspwm/src/rofi-themes/shared.rasi <<EOF
// Rofi colors for Aing

* {
    font: "Terminess Nerd Font Mono Bold 10";
    background: #161a22;
    background-alt: #161a22E0;
    foreground: #cadee7;
    selected: #E3C4BA;
    active: #6E91BA;
    urgent: #927887;
    img-background: url("~/.config/bspwm/rices/aing/rofi.webp", width);
    main-bg: #161a22E0;
    main-fg: #cadee7;
    main-fg-alt: #161a22E0;
    select-bg: #E3C4BA;
    select-fg: #161a22;
}
EOF
sed -i "$HOME/.config/bspwm/src/rofi-themes/Window.rasi" \
    -e '17s|\(font:\s*\).*|\1"Terminess Nerd Font Mono Bold 10";|' \
    -e 's|\(font-weight:\s*\).*|\1bold;|' \
    -e 's|\(background:\s*\).*|\1#161a22;|' \
    -e 's|\(background-alt:\s*\).*|\1#161a22E0;|' \
    -e 's|\(foreground:\s*\).*|\1#cadee7;|' \
    -e 's|\(selected:\s*\).*|\1#E3C4BA;|' \
    -e 's|\(highlight:\s*\).*|\1#6E91BA;|' \
    -e 's|\(urgent:\s*\).*|\1#927887;|' \
    -e 's|\(window-format:\s*\).*|\1" {c}  󰇙  {t}";|' \
    -e '25s|\(on:\s*\).*|\1#55535c;|' \
    -e '26s|\(off:\s*\).*|\1#927887;|' \
    -e '60s|\(background-color:\s*\).*|\1@selected;|' \
    -e '61s|\(text-color:\s*\).*|\1@background-alt;|' \
    -e '67s|\(background-color:\s*\).*|\1@selected;|' \
    -e '68s|\(text-color:\s*\).*|\1@background-alt;|' \
    -e '72s|\(border-color:\s*\).*|\1@selected;|' \
    -e 's|\(background-image:.*rices/\)[^/]*|\1aing|'
}

# Set color cava #bak-e "78s/gradient_color_1 = .*/gradient_color_1 = '#D2ACA9'/g"
set_cava() {
  sed -i "$HOME/.config/cava/config" \
    -e "s/foreground = .*/foreground = 'cyan'/g"
}

# Appearance
set_appearance() {
  XFILE="$BDIR/xsettingsd"
  GTK2FILE="$HOME/.gtkrc-2.0"
  GTK3FILE="$HOME/.config/gtk-3.0/settings.ini"

  # apply gtk theme, icons, cursor & fonts
  if [[ `pidof xsettingsd` ]]; then
    sed -i -e "s|Net/ThemeName .*|Net/ThemeName \"amarena\"|g" ${XFILE}
    sed -i -e "s|Net/IconThemeName .*|Net/IconThemeName \"Nordzy-pink-dark\"|g" ${XFILE}
    sed -i -e "s|Gtk/CursorThemeName .*|Gtk/CursorThemeName \"phinger-cursors\"|g" ${XFILE}
  else
    sed -i -e "s/gtk-font-name=.*/gtk-font-name=\"Noto Sans 9\"/g" ${GTK2FILE}
    sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=\"amarena\"/g" ${GTK2FILE}
    sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=\"Nordzy-pink-dark\"/g" ${GTK2FILE}
    sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=\"phinger-cursors\"/g" ${GTK2FILE}
    
    sed -i -e "s/gtk-font-name=.*/gtk-font-name=Noto Sans 9/g" ${GTK3FILE}
    sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=amarena/g" ${GTK3FILE}
    sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=Nordzy-pink-dark/g" ${GTK3FILE}
    sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=phinger-cursors/g" ${GTK3FILE}
  fi
  
  # inherit cursor theme
  if [[ -f "$HOME"/.icons/default/index.theme ]]; then
    sed -i -e "s/Inherits=.*/Inherits=phinger-cursors/g" "$HOME"/.icons/default/index.theme
  fi  
}

# Launch the bar and or eww widgets
launch_bars() {

  for mon in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$mon polybar -q aing-bar -c ${rice_dir}/config.ini &
  done

}

### ---------- Apply Configurations ---------- ###

set_bspwm_config
set_alacritty_config
set_kitty_config
set_picom_config
set_stalonetray_config
launch_bars
set_dunst_config
set_eww_colors
set_jgmenu_colors
set_launcher_config
set_cava
set_appearance