#!/usr/bin/env bash
#  ╔═╗╔═╗╔═╗╔═╗  ╦  ╔═╗╦ ╦╔╗╔╔═╗╦ ╦╔═╗╦═╗
#  ╠═╣╠═╝╠═╝╚═╗  ║  ╠═╣║ ║║║║║  ╠═╣║╣ ╠╦╝
#  ╩ ╩╩  ╩  ╚═╝  ╩═╝╩ ╩╚═╝╝╚╝╚═╝╩ ╩╚═╝╩╚═
#	Script to control apps launcher
#   Author: z0mbi3
#	Modified: me

# From here you can control your favorite applications for all themes.

WIDGET_DIR="$HOME/.config/bspwm/eww"

    case "$1" in
    --menu)
      #rofi -show drun -theme $HOME/.config/bspwm/rices/${RICETHEME}/launcher.rasi
      rofi -show drun -theme $HOME/.config/bspwm/scripts/Launcher.rasi
      ;;
    --rice)
      RiceSelector
      ;;
    --clip)
      #rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}' -theme $HOME/.config/bspwm/scripts/Clipboard.rasi
      rofi -theme $HOME/.config/bspwm/scripts/Clipboard.rasi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'; xdotool type "$(xclip -o -selection clipboard)"
      ;;
    --terminal)
      alacritty
      ;;
    --floating)
      alacritty --class FloaTerm,Alacritty -o window.dimensions.lines=22 window.dimensions.columns=90
      ;;
    --update)
      alacritty --hold --class FloaTerm,Alacritty -o window.dimensions.lines=22 window.dimensions.columns=90 -e Updates --update-system
      ;;
    --checkupdates)
      alacritty --hold --class Updating,Alacritty -o window.dimensions.lines=22 window.dimensions.columns=47 -e Updates --print-updates
      ;;
    --ranger)
      alacritty --class FloaTerm,Alacritty -o window.dimensions.lines=14 window.dimensions.columns=90 -e ranger
      ;;
    --nvim)
      alacritty -e nvim
      ;;
    --music)
      alacritty --class FloaTerm,Alacritty -o window.dimensions.lines=18 window.dimensions.columns=67 -e ncmpcpp
      ;;
    --htop)
      alacritty -e htop
      ;;
    --spot)
      spotify
      ;;
    --fetch)
      alacritty --hold --class Sysfetch,Alacritty -o window.dimensions.lines=26 window.dimensions.columns=40 -e ~/.local/bin/sysfetch
      ;;
    #Apps
    --filemanager)
      thunar
      ;;
    --browser)
      firefox
      ;;
    --editor)
      geany
      ;;
    --telegram)
      telegram-desktop
      ;;
    --whats)
      whatsapp-nativefier --disable-gpu
      ;;
    --soundcontrol)
      pavucontrol
      ;;
    # Eww Widgets
    --powermenu)
      eww -c "$WIDGET_DIR" open --toggle powermenu
      ;;
    --usercard)
      eww -c "$WIDGET_DIR" open --toggle launchermenu
      ;;
    --player)
      eww -c "$WIDGET_DIR" open --toggle music
      ;;
    --calendar)
      eww -c "$WIDGET_DIR" open --toggle date
      ;;
    *)
      echo "Opción no válida"
      ;;
    esac
