#!/usr/bin/env bash
#  ╦═╗╦╔═╗╔═╗  ╔═╗╔═╗╦  ╔═╗╔═╗╔╦╗╔═╗╦═╗  - modified by me 
#  ╠╦╝║║  ║╣   ╚═╗║╣ ║  ║╣ ║   ║ ║ ║╠╦╝  - 
#  ╩╚═╩╚═╝╚═╝  ╚═╝╚═╝╩═╝╚═╝╚═╝ ╩ ╚═╝╩╚═  - original z0mbi3

bspwm_dir="$HOME/.config/bspwm"
current_rice_file="$bspwm_dir/.rice"
preview_dir="$bspwm_dir/rices/${options[*]}"
rofi_command="rofi -dmenu -theme $bspwm_dir/scripts/RiceSelector.rasi"
#read -r current_rice < "$HOME"/.config/bspwm/.rice
# Variables to try to define the correct size of the images for your resolution
monitor_res=$(xdpyinfo | awk '/dimensions/{print $2}' | cut -d 'x' -f1)
monitor_scale=$(xdpyinfo | awk '/resolution/{print $2}' | cut -d 'x' -f1)
monitor_res=$(( monitor_res * 17 / monitor_scale ))
rofi_override="element-icon{size:${monitor_res}px;}"

# List rices
options=()
index=0
selected_index=0
current_rice=$(< "$current_rice_file")

for rice_dir in "$bspwm_dir"/rices/*/; do
    rice_name=$(basename "$rice_dir")
    options+=("$rice_name")

    # Check if the current rice matches the current iteration rice
    if [[ "$current_rice" == "$rice_name" ]]; then
        selected_index=$index
    fi

    ((index++))
done

# Show the rofi selection menu with the starting point set to the current rice and store the result in a variable.
#selected=$(printf "%s\n" "${options[@]}" | $rofi_command -selected-row "$selected_index")
selected=$(printf "%s\n" "${options[@]}" | while read -r A ; do  echo -en "$A\x00icon\x1f${preview_dir}$A/preview.webp\n" ; done | $rofi_command -theme-str "$rofi_override" -selected-row "$selected_index")

# If a valid option was selected, write the value to the configuration file and restart BSPWM.
[[ -n "$selected" && "$selected" != "$current_rice" ]] || exit 1
echo "$selected" > "$current_rice_file"
bspc wm -r

exit 0