#!/bin/sh

# Common Temperature Sensor Paths
PATHS="/sys/class/thermal/thermal_zone*/temp
/sys/devices/platform/coretemp.*/hwmon/hwmon*/temp*_input
/sys/devices/virtual/thermal/thermal_zone*/temp
/sys/devices/virtual/thermal/cooling_device*/temp
/sys/bus/acpi/devices/LNXTHERM:*/thermal_zone/temp
/sys/devices/platform/samsung/thermal/temperature
/sys/class/hwmon/hwmon*/temp*_input
/sys/devices/pci*/*/hwmon/hwmon*/temp1_input
/sys/devices/platform/thinkpad_hwmon/hwmon/hwmon*/temp*_input
/sys/devices/virtual/thermal/cooling_device*/cur_state"

find_cpu_temp() {
    max_temp=0

    for path in $PATHS; do
        for file in $(ls $path 2>/dev/null); do
            if [ -f "$file" ]; then
                current_temp=$(awk '{print int($1/1000)}' "$file" 2>/dev/null)

                # Check if it's a number
                case "$current_temp" in
                    ''|*[!0-9]*)
                        continue
                        ;;
                esac

                if [ "$current_temp" -gt "$max_temp" ]; then
                    max_temp=$current_temp
                fi
            fi
        done
    done

    if [ "$max_temp" -gt 0 ]; then
        echo "$max_temp"
    else
        echo "null"
    fi
}

TEMP=$(find_cpu_temp)
echo "${TEMP}°"
