#!/usr/bin/env bash
## GameMode script
## Disables picom composer, notifications and configure the processor in performance mode
## original z0mbi3

CACHE_FILE="$HOME/.cache/$(whoami)/gamemode_state"
CPU_GOVERNOR_PATH="/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"

mkdir -p "$(dirname "$CACHE_FILE")"
[[ -f "$CACHE_FILE" ]] || echo Off >"$CACHE_FILE"

get_state() {
	cat "$CACHE_FILE"
}

set_cpu_governor() {
    local governor=$1
    echo $governor | pkexec tee /sys/devices/system/cpu/*/cpufreq/scaling_governor
}

gamemode_on() {
	dunstctl set-paused true
	pkill -f picom
	set_cpu_governor performance
	echo On >"$CACHE_FILE"
}

gamemode_off() {
	dunstctl set-paused false
	picom --config "$HOME"/.config/bspwm/picom.conf &
	set_cpu_governor ondemand
	echo Off >"$CACHE_FILE"
}

toggle() {
	if [[ $(get_state) == "Off" ]]; then
        gamemode_on
    else
        gamemode_off
    fi
}


case "$1" in
    --toggle) toggle ;;
    --status) get_state ;;
    *) echo "Usage: $0 [--toggle|--status]" ;;
esac