#!/usr/bin/env bash

CACHE_DIR="$HOME/.cache/$USER"
CACHE_FILE="$CACHE_DIR/gamemode_state"
CPU_GOVERNOR_PATH="/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"

# Create cache directory if it does not exist
mkdir -p "$CACHE_DIR"
[[ -f "$CACHE_FILE" ]] || echo "Off" > "$CACHE_FILE"

# Function to obtain the current state of Game Mode
get_state() {
    head -n 1 "$CACHE_FILE" 2>/dev/null || echo "Off"
}

# Function to change CPU governor
set_cpu_governor() {
    local governor=$1
    echo "$governor" | pkexec tee /sys/devices/system/cpu/*/cpufreq/scaling_governor >/dev/null
}

# Function to activate Game Mode
gamemode_on() {
    local prev_governor
    prev_governor=$(cat "$CPU_GOVERNOR_PATH")
    echo "$prev_governor" > "$CACHE_DIR/cpu_governor"

	dunstctl set-paused true
    pkill -f picom
    set_cpu_governor performance
    echo "On" > "$CACHE_FILE"

}

# Function to deactivate Game Mode
gamemode_off() {
    dunstctl set-paused false
    picom --config "$HOME/.config/bspwm/src/config/picom.conf" &

    local prev_governor
    prev_governor=$(cat "$CACHE_DIR/cpu_governor")
    set_cpu_governor "$prev_governor"

    echo "Off" > "$CACHE_FILE"

    dunstify -i games "Game Mode" "Game Mode disabled. Picom restarted, notifications resumed and CPU $prev_governor restored."
}

# Function to toggle Game Mode
toggle() {
    if [[ $(get_state) == "Off" ]]; then
        gamemode_on
    else
        gamemode_off
    fi
}

case "$1" in
    --toggle) toggle ;;
    --status) get_state ;;
    *)        echo "Uso: $0 [--toggle|--status]" ;;
esac
