#!/usr/bin/env bash

cache_file=$HOME/.cache/$(whoami)/redshift_state

mkdir -p "$(dirname "$cache_file")"
[[ -f "$cache_file" ]] || echo off > "$cache_file"

get_state() {
    cat "$cache_file"
}

disable_redshift() {
    redshift -x >/dev/null 2>&1
    echo off >"$cache_file"
}

enable_redshift() {
    redshift -x
    redshift -O 3350
    echo on >"$cache_file"
}

toggle() {
    if [[ $(get_state) == "on" ]]; then
        disable_redshift
    else
        enable_redshift
    fi
}

case $1 in
    state) get_state ;;
    toggle) toggle ;;
esac